/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"

#include "bar_ewmhtags.h"
#include "bar_ltsymbol.h"
#include "bar_powerline_status.h"
#include "bar_status.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_awesomebar.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "attachx.h"
#include "autostart.h"
#include "cfacts.h"
#include "cyclelayouts.h"
#include "dragmfact.h"
#include "fullscreen.h"
#include "movestack.h"
#include "pertag.h"
#include "push.h"
#include "restartsig.h"
#include "scratchpad.h"
#include "selfrestart.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_bstackhoriz.h"
#include "layout_centeredmaster.h"
#include "layout_centeredfloatingmaster.h"
#include "layout_columns.h"
#include "layout_deck.h"
#include "layout_fibonacci.h"
#include "layout_grid.h"
#include "layout_monocle.h"
#include "layout_tile.h"

