/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_ewmhtags.c"
#include "bar_ltsymbol.c"
#include "bar_powerline_status.c"
#include "bar_status.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "attachx.c"
#include "autostart.c"
#include "cfacts.c"
#include "cyclelayouts.c"
#include "fullscreen.c"
#include "movestack.c"
#include "pertag.c"
#include "push.c"
#include "restartsig.c"
#include "scratchpad.c"
#include "selfrestart.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_bstackhoriz.c"
#include "layout_centeredmaster.c"
#include "layout_centeredfloatingmaster.c"
#include "layout_columns.c"
#include "layout_deck.c"
#include "layout_fibonacci.c"
#include "layout_grid.c"
#include "layout_monocle.c"
#include "layout_tile.c"

